
%net = imagePretrainedNetwork("resnet50",NumClasses=numClasses);
net = imagePretrainedNetwork("resnet18",NumClasses=numClasses);

options = trainingOptions("sgdm", ...
    InitialLearnRate=0.01, ...
    MiniBatchSize=32, ...
    MaxEpochs= 1, ...
    Verbose= false, ...
    ValidationData=valData, ...
    ValidationFrequency=100, ...
    ValidationPatience=5, ...
    Metrics="accuracy", ...
    Plots="training-progress");

trainedNet = trainnet(trainData,net,"binary-crossentropy",options);
