close all;

%net = imagePretrainedNetwork("resnet50",NumClasses=numClasses);
net = imagePretrainedNetwork("resnet18",NumClasses=numClasses);

layer = sigmoidLayer('Name', 'sig1');

net = replaceLayer(net,"prob",layer);

analyzeNetwork(net);

% net = freezeNetwork(net,LayerNamesToIgnore="Logits"); % pour mobilenetv2
net = freezeNetwork(net,LayerNamesToIgnore="fc1000"); % pour resnet18/resnet50

options = trainingOptions("adam", ...
    InitialLearnRate=0.01, ...
    MiniBatchSize=32, ...
    MaxEpochs= 1, ...
    Verbose= false, ...
    ValidationData=valData, ...
    ValidationFrequency=100, ...
    ValidationPatience=5, ...
    Metrics="accuracy", ...
    Plots="training-progress");

trainedNet = trainnet(trainData,net,"binary-crossentropy",options);
